### ISSUE TITLE
Overflow Test

### ISSUE THREAD

**Issue by odensc** [thesbros/electron#1]
@radencode - I didn't want to clutter up the electron repo more.

I uploaded a new test version, I have tested it and fixes both issues. Would you confirm?

Download: [R.zip](https://github.com/thesbros/electron/releases/download/v1.6.1/R.zip)

**Comment by radencode** [comment]
@thesbros No worries

Yes it does, thank you. I've been fighting this for a while. Good job. ;) 

What were you able to fix it?

**Comment by odensc** [comment]
@radencode This is how I fixed it: https://github.com/thesbros/electron/commit/f0ea66582ac4ebeae240660a4c60ce63f2464d18

I'm going to submit a PR tomorrow once I fix the DPI > 100% issues with it.

**Comment by radencode** [comment]
@thesbros Thank you, sounds great.

**Comment by radencode** [comment]
@thesbros I just updated my application repo with your electron build and it works just fine and both issues are completely fixed on 100%, 125% and 200% DPI.

I'm not sure there is any DPI issue, are you getting an issue with it?

**Comment by odensc** [comment]
@radencode Yes - when I increase my DPI the window gets cut off like before, you need to sign out and back in for the DPI to correctly apply. Did you do that and it still works?

**Comment by radencode** [comment]
@thesbros Huh that's weird?!

Yes I did sign out and tested it. In fact I have a 4K laptop which is 300% by default and it works fine.

**Comment by odensc** [comment]
@radencode

Perhaps it's not as noticeable in your application? I made a page with a 1px red border around it, and with higher DPI you can't see them.

[100% DPI (zoom in to see borders)](http://i.imgur.com/4l5Sccq.png)
[175% DPI](http://i.imgur.com/OPPAcWJ.png)

**Comment by radencode** [comment]
@thesbros yes that very well could be how it is. I'm going to test it tonight and let you know.

**Comment by radencode** [comment]
@thesbros I just tested it on my laptop which has 300% dpi and yes it does have ~2px of overlap. 

Have you submitted a PR yet?

**Comment by odensc** [comment]
Yes I've submitted PR8808.

I fixed some of the DPI issues in that PR - but the cut off seems to be a separate issue. On high DPI, the edges of frameless windows will be cut off a by a pixel or two, even unmaximized. This doesn't happen on Electron 1.4.x - only 1.5 and higher.

**Comment by radencode** [comment]
@thesbros Yeah that makes sense, well 1 or 2px is not a big issue vs how it was before so thank you very much for the fix.

**Comment by radencode** [comment]
@thesbros have you fixed the DPI issue yet?

**Comment by odensc** [comment]
@radencode Yes, I have [in this PR.](http://bit.ly/2mNktLu) Just the issue is that overriding the event to fix the DPI issue, causes rounded edges when the window is not maximized. That is the only issue right now.

**Comment by radencode** [comment]
Hey @thesbros I am using electron-edge with electron and it tells me that electron-edge is not pre-compiled for node v7.4.0. I see that in your electron build the node.dll file is v7.4.0 is there a way we can build it with node.dll v6.5.0?

**Comment by radencode** [comment]
I tried to re-compile electron-edge but their instructions are very confusing and I am getting no where.

**Comment by odensc** [comment]
@radencode Sorry, I'm not familiar with electron-edge. Perhaps replacing the node 7 dll with a node 6 dll from an older version of electron would work?

**Comment by radencode** [comment]
@thesbros Yeah I tried that to see but it gave me and error. Alright I thought I should ask you just in case. Thank you.

**Comment by radencode** [comment]
@thesbros Hey man when you built that fix for the oversized window you built with node v6.5.0, how did you do that. Because when I build it right now it comes out v7.4.0 and I need v6.5.0. Can you help please? And thank you for all of your help.

**Comment by radencode** [comment]
@thesbros I fixed that issue but now my issue is that when I run electron-packager the border issue comes back. Do you know if electron-packager can use the node_module/electron to build the app?

**Comment by thesbros** [comment]
Seems not. There is an old issue about it (#187) - The only option is to use electron-builder which is generally more configurable.

**Comment by odensc** [comment]
Seems not. There is an old issue about it (187) - The only option is to use electron-builder which is generally more configurable.

**Comment by radencode** [comment]
@thesbros I was looking into that as well. I will give it a go, thank you.
